
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - relationships:
              to: ref('my_first_dbt_model')
              field: id
  - name: snowflake_customer_purchases
    description: "the total purchases for each customer in snowflake sample data"
    columns:
      - name: c_custkey
        tests:
          - unique
          - not_null
  - name: cumulative_orders_by_date
    description: "the cumulative sales per date"
    columns:
      - name: order_date
        tests: 
          - unique
          - not_null
  - name: dates